#creating copies of .bashrc into /ctool/users/
sudo cp /home/ctools/.bashrc /ctools/users/ctools.bashrc
sudo cp /home/steve/.bashrc /ctools/users/steve.bashrc
sudo cp /home/john/.bashrc /ctools/users/john.bashrc
sudo cp /home/vince/.bashrc /ctools/users/vince.bashrc
sudo cp /home/ctj-jonathan/.bashrc /ctools/users/ctj-jonathan.bashrc
sudo cp /home/ctj-counter1/.bashrc /ctools/users/ctj-counter1.bashrc
sudo cp /home/ctj-counter2/.bashrc /ctools/users/ctj-counter2.bashrc
sudo cp /home/ctj-donovan/.bashrc /ctools/users/ctj-donovan.bashrc
sudo cp /home/ctj-lizzie/.bashrc /ctools/users/ctj-lizzie.bashrc
sudo cp /home/ctj-lourens/.bashrc /ctools/users/ctj-lourens.bashrc
sudo cp /home/ctj-penny/.bashrc /ctools/users/ctj-penny.bashrc
sudo cp /home/ctj-ray/.bashrc /ctools/users/ctj-ray.bashrc
sudo cp /home/ctj-rosa/.bashrc /ctools/users/ctj-rosa.bashrc
sudo cp /home/ctj-sam/.bashrc /ctools/users/ctj-sam.bashrc
sudo cp /home/ctj-lynn/.bashrc /ctools/users/ctj-lynn.bashrc
sudo cp /home/ctj-store/.bashrc /ctools/users/ctj-store.bashrc
sudo cp /home/ctj-werner/.bashrc /ctools/users/ctj-werner.bashrc
sudo cp /home/ctj-yvonne/.bashrc /ctools/users/ctj-yvonne.bashrc
sudo cp /home/ctn-adhir/.bashrc /ctools/users/ctn-adhir.bashrc
sudo cp /home/ctn-niresh/.bashrc /ctools/users/ctn-niresh.bashrc
sudo cp /home/ctn-livell/.bashrc /ctools/users/ctn-livell.bashrc
sudo cp /home/ctn-randhir/.bashrc /ctools/users/ctn-randhir.bashrc
sudo cp /home/ctn-store/.bashrc /ctools/users/ctn-store.bashrc
sudo cp /home/sfj-bianca/.bashrc /ctools/users/sfj-bianca.bashrc
sudo cp /home/sfj-chesley/.bashrc /ctools/users/sfj-chesley.bashrc
sudo cp /home/sfj-craig/.bashrc /ctools/users/sfj-craig.bashrc
sudo cp /home/sfj-daleen/.bashrc /ctools/users/sfj-daleen.bashrc
sudo cp /home/sfj-gert/.bashrc /ctools/users/sfj-gert.bashrc
sudo cp /home/sfj-kevin/.bashrc /ctools/users/sfj-kevin.bashrc
sudo cp /home/sfj-sagran/.bashrc /ctools/users/sfj-sagran.bashrc
sudo cp /home/sfj-store/.bashrc /ctools/users/sfj-store.bashrc
sudo cp /home/csc-bianca/.bashrc /ctools/users/csc-bianca.bashrc
sudo cp /home/csc-kevin/.bashrc /ctools/users/csc-kevin.bashrc
sudo cp /home/csc-rudie/.bashrc /ctools/users/csc-rudie.bashrc
sudo cp /home/csc-store/.bashrc /ctools/users/csc-store.bashrc
sudo cp /home/csc-suzanne/.bashrc /ctools/users/csc-suzanne.bashrc
sudo cp /home/ctj-kim/.bashrc /ctools/users/ctj-kim.bashrc
sudo cp /home/ctj-prince/.bashrc /ctools/users/ctj-prince.bashrc
sudo cp /home/ctj-ricardo/.bashrc /ctools/users/ctj-ricardo.bashrc
sudo cp /home/ctj-christo/.bashrc /ctools/users/ctj-christo.bashrc
sudo cp /home/ctj-themba/.bashrc /ctools/users/ctj-themba.bashrc
sudo cp /home/ctn-viresh/.bashrc /ctools/users/ctn-viresh.bashrc
sudo cp /home/ctn-dylan/.bashrc /ctools/users/ctn-dylan.bashrc
sudo cp /home/sfj-arno/.bashrc /ctools/users/sfj-arno.bashrc
