#Copying the stored .bashrc files off /ctools/uses/ to each individual /home/ folder
sudo cp /ctools/users/ctools.bashrc /home/ctools/.bashrc
sudo cp /ctools/users/steve.bashrc /home/steve/.bashrc
sudo cp /ctools/users/john.bashrc /home/john/.bashrc
sudo cp /ctools/users/vince.bashrc /home/vince/.bashrc
sudo cp /ctools/users/ctj-jonathan.bashrc /home/ctj-jonathan/.bashrc
sudo cp /ctools/users/ctj-counter1.bashrc /home/ctj-counter1/.bashrc
sudo cp /ctools/users/ctj-counter2.bashrc /home/ctj-counter2/.bashrc
sudo cp /ctools/users/ctj-donovan.bashrc /home/ctj-donovan/.bashrc
sudo cp /ctools/users/ctj-lizzie.bashrc /home/ctj-lizzie/.bashrc
sudo cp /ctools/users/ctj-lourens.bashrc /home/ctj-lourens/.bashrc
sudo cp /ctools/users/ctj-penny.bashrc /home/ctj-penny/.bashrc
sudo cp /ctools/users/ctj-ray.bashrc /home/ctj-ray/.bashrc
sudo cp /ctools/users/ctj-rosa.bashrc /home/ctj-rosa/.bashrc
sudo cp /ctools/users/ctj-sam.bashrc /home/ctj-sam/.bashrc
sudo cp /ctools/users/ctj-lynn.bashrc /home/ctj-lynn/.bashrc
sudo cp /ctools/users/ctj-store.bashrc /home/ctj-store/.bashrc
sudo cp /ctools/users/ctj-werner.bashrc /home/ctj-werner/.bashrc
sudo cp /ctools/users/ctj-yvonne.bashrc /home/ctj-yvonne/.bashrc
sudo cp /ctools/users/ctn-adhir.bashrc /home/ctn-adhir/.bashrc
sudo cp /ctools/users/ctn-niresh.bashrc /home/ctn-niresh/.bashrc
sudo cp /ctools/users/ctn-livell.bashrc /home/ctn-livell/.bashrc
sudo cp /ctools/users/ctn-randhir.bashrc /home/ctn-randhir/.bashrc
sudo cp /ctools/users/ctn-store.bashrc /home/ctn-store/.bashrc
sudo cp /ctools/users/sfj-bianca.bashrc /home/sfj-bianca/.bashrc
sudo cp /ctools/users/sfj-chesley.bashrc /home/sfj-chesley/.bashrc
sudo cp /ctools/users/sfj-craig.bashrc /home/sfj-craig/.bashrc
sudo cp /ctools/users/sfj-daleen.bashrc /home/sfj-daleen/.bashrc
sudo cp /ctools/users/sfj-gert.bashrc /home/sfj-gert/.bashrc
sudo cp /ctools/users/sfj-kevin.bashrc /home/sfj-kevin/.bashrc
sudo cp /ctools/users/sfj-sagran.bashrc /home/sfj-sagran/.bashrc
sudo cp /ctools/users/sfj-store.bashrc /home/sfj-store/.bashrc
sudo cp /ctools/users/csc-bianca.bashrc /home/csc-bianca/.bashrc
sudo cp /ctools/users/csc-kevin.bashrc /home/csc-kevin/.bashrc
sudo cp /ctools/users/csc-rudie.bashrc /home/csc-rudie/.bashrc
sudo cp /ctools/users/csc-store.bashrc /home/csc-store/.bashrc
sudo cp /ctools/users/csc-suzanne.bashrc /home/csc-suzanne/.bashrc
sudo cp /ctools/users/ctj-kim.bashrc /home/ctj-kim/.bashrc
sudo cp /ctools/users/ctj-prince.bashrc /home/ctj-prince/.bashrc
sudo cp /ctools/users/ctj-ricardo.bashrc /home/ctj-ricardo/.bashrc
sudo cp /ctools/users/ctn-viresh.bashrc /home/ctn-viresh/.bashrc
sudo cp /ctools/users/sfj-arno.bashrc /home/sfj-arno/.bashrc
sudo cp /ctools/users/ctn-dylan.bashrc /home/ctn-dylan/.bashrc
sudo cp /ctools/users/ctj-christo.bashrc /home/ctj-christo/.bashrc
sudo cp /ctools/users/ctj-themba.bashrc /home/ctj-themba/.bashrc
