#Installing Passwords for each new user account created
#sudo passwd ctools    ctools
sudo passwd steve thutmes
sudo passwd john thrcanbonly1
sudo passwd vince vince
sudo passwd ctj-jonathan ctj-sales
sudo passwd ctj-counter1 ctj-counter
sudo passwd ctj-counter2 ctj-counter
sudo passwd ctj-donovan blakkie
sudo passwd ctj-lizzie arnie
sudo passwd ctj-lourens frodo
sudo passwd ctj-penny creditors
sudo passwd ctj-ray coelecanth
sudo passwd ctj-rosa ctj-rosa
sudo passwd ctj-sam ctj-sam
sudo passwd ctj-lynn ctj-lynn
sudo passwd ctj-store security
sudo passwd ctj-werner fritz
sudo passwd ctj-yvonne ctj-yvonne
sudo passwd ctn-adhir ctn-adhir
sudo passwd ctn-niresh sentra
sudo passwd ctn-livell ctn-livell
sudo passwd ctn-randhir home
sudo passwd ctn-store ctn-store
sudo passwd sfj-bianca lucille
sudo passwd sfj-chesley etude
sudo passwd sfj-craig profits
sudo passwd sfj-daleen sfj-daleen
sudo passwd sfj-gert bigprofits
sudo passwd sfj-kevin sfj-kevin
sudo passwd sfj-sagran sfj-sagran
sudo passwd sfj-store sfj-store
sudo passwd csc-bianca csc-bianca
sudo passwd csc-kevin csc-kevin
sudo passwd csc-rudie bigprofit
sudo passwd csc-store csc-store
sudo passwd csc-suzanne admin
sudo passwd ctj-kim ctj-kim
sudo passwd ctj-prince ctj-prince
sudo passwd ctj-ricardo ctj-ricardo
sudo passwd ctj-christo christo
sudo passwd ctj-themba ctj-themba
sudo passwd ctn-viresh viresh
sudo passwd ctn-dylan ctn-dylan
sudo passwd sfj-arno sfj-stores
