#Set up of all users into the ctools group.
#sudo usermod -g ctools ctools    ctools
sudo usermod -g ctools steve
sudo usermod -g ctools john
sudo usermod -g ctools vince
sudo usermod -g ctools ctj-jonathan
sudo usermod -g ctools ctj-counter1
sudo usermod -g ctools ctj-counter2
sudo usermod -g ctools ctj-donovan
sudo usermod -g ctools ctj-lizzie
sudo usermod -g ctools ctj-lourens
sudo usermod -g ctools ctj-penny
sudo usermod -g ctools ctj-ray
sudo usermod -g ctools ctj-rosa
sudo usermod -g ctools ctj-sam
sudo usermod -g ctools ctj-lynn
sudo usermod -g ctools ctj-store
sudo usermod -g ctools ctj-werner
sudo usermod -g ctools ctj-yvonne
sudo usermod -g ctools ctn-adhir
sudo usermod -g ctools ctn-niresh
sudo usermod -g ctools ctn-livell
sudo usermod -g ctools ctn-randhir
sudo usermod -g ctools ctn-store
sudo usermod -g ctools sfj-bianca
sudo usermod -g ctools sfj-chesley
sudo usermod -g ctools sfj-craig
sudo usermod -g ctools sfj-daleen
sudo usermod -g ctools sfj-gert
sudo usermod -g ctools sfj-kevin
sudo usermod -g ctools sfj-sagran
sudo usermod -g ctools sfj-store
sudo usermod -g ctools csc-bianca
sudo usermod -g ctools csc-kevin
sudo usermod -g ctools csc-rudie
sudo usermod -g ctools csc-store
sudo usermod -g ctools csc-suzanne
sudo usermod -g ctools ctj-kim
sudo usermod -g ctools ctj-prince
sudo usermod -g ctools ctj-ricardo
sudo usermod -g ctools ctj-christo
sudo usermod -g ctools ctj-themba
sudo usermod -g ctools ctn-viresh
sudo usermod -g ctools ctn-dylan
sudo usermod -g ctools sfj-arno
