Screen Setup

Y


Y

100


copy
<ctj>drlaserco01
<spl>CtjStat
Y

copy
<GRC>drlaserco02
<spl>GRCStat
Y

copy
<ctn>drlaserco03
<spl>CtnStat
Y

copy
<ctc>drlaserco04
<spl>CtcStat
Y

copy
<sfj>drlaserco07
<spl>SfjStat
Y

copy
<CSC>drlaserco08
<spl>CSCStat
Y

Path
Win
SPL

/z
ct*stat Sf*stat cs*Stat
<Image>State.Zip


Path
Win
Program

Type
<Temp>BranchZipMessage

Submit
PrepEMailStatements.Sub
