Screen Setup

Y


Y

100

Path
Win
CTJ
/u
m*p
drl*

Path
Win
GRC
/u
m*p
drl*

Path
Win
ctn
/u
m*p
drl*

Path
Win
sfj
/u
m*p
drl*


Path
Win
CSC
/u
m*p
drl*

copy
<ctj>drlaserco01
<Image>CtjStat
Y

copy
<GRC>drlaserco02
<Image>GRCStat
Y

copy
<ctn>drlaserco03
<Image>CtnStat
Y

copy
<sfj>drlaserco07
<Image>SfjStat
Y

copy
<CSC>drlaserco08
<Image>CSCStat
Y

Path
Win
Image

;/z
;ct*stat Sf*stat cs*Stat G*Stat
;<Image>State.Zip
;

Path
Win
Program

Type
<Temp>BranchZipMessage


PrepEMailStatements
