Screen Setup

Y


Y

100

Path
Win
Zip

Orthello


Type
<Temp>ZipMessage1

1

Lcop
[f0]<Src>*



Y


Type
<Temp>ZipMessage2-1

1

Lcop
[f0]<Src>*



Y



Type
<Temp>ZipMessage3-1

1

Lcop
[F0]<Src>*



Y



Type
<Temp>ZipMessage4

1

Lcop
[F0]<Src>*



Y


Type
<Temp>ZipMessage5

1

Lcop
[f0]<Copy>*



Y



Lcop
[f0]<Chlfd>*



Y

Lcop
[f0]<Program>*



Y


Lcop
[f0]<Temp>*



Y

****** LCopy of all zip files from F0 complete *****
