Screen Setup

Y


Y

100

Path
Win
Zip

Orthello


Type
<Temp>ZipMessage1

1

Lcop
Dr.Zip

[f0]<Src>

Y


Type
<Temp>ZipMessage2-1

1

Lcop
St1.Zip

[f0]<Src>

Y


Type
<Temp>ZipMessage2-2

1

Lcop
St2.Zip

[f0]<Src>

Y



Type
<Temp>ZipMessage3-1

1

Lcop
Sl1.Zip

[f0]<Src>

Y


Type
<Temp>ZipMessage3-2

1

Lcop
Sl2.Zip

[f0]<Src>

Y



Type
<Temp>ZipMessage4

1

Lcop
Gl.Zip

[f0]<Src>

Y

Lcop
Cb.Zip

[f0]<Src>

Y


Lcop
Cr.Zip

[f0]<Src>

Y


Lcop
Bm.Zip

[f0]<Src>

Y

Lcop
Menu.Zip

[f0]<Src>

Y


Lcop
Co.Zip

[f0]<Src>

Y



Type
<Temp>ZipMessage5

1

Lcop
copy.Zip

[f0]<Copy>

Y



Lcop
Chlfd.Zip

[f0]<Chlfd>

Y

Lcop
[Win]<Program>CoForms.Lib

[f0]<Program>

Y

Lcop
sub.Zip

[f0]<Program>

Y

Lcop
Temp.Zip

[f0]<Temp>

Y

****** LCopy of all zip files complete *****
