***** DELETING OF FILES FROM SPECIFIED DIRECTORIES STARTS *****

*** FILES UPDATED ON 4TH NOVEMBER 2003 ****

Screen Setup

Y


Y

100

Path
New
Sys

Orthello



Delete
<$000>*


Delete
<$Gps>*


Delete
<6Bar>*


Delete
<6BarInd>*


Delete
<6Br>*


Delete
<APTNet>*


Delete
<APTNetGen>*


Delete
<Beltel>*


Delete
<Booze>*


Delete
<Cobol2>*


Delete
<Company>*


Delete
<Comp2000>*


Delete
<Comp2001>*


Delete
<Comp2002>*


Delete
<Company>*


Delete
<CR>*


Delete
<CRZip>*


Delete
<CTC>*


Delete
<CTJ>*


Delete
<CTN>*


Delete
<Data>*


Delete
<DataInd>*


Delete
<DB>*


Delete
<Dr>*


Delete
<DrZip>*


Delete
<Exec>*


Delete
<Fms.Fp>*


Delete
<Forms>*


Delete
<Formsc>*


Delete
<FPlus>*


Delete
<FSE>*


Delete
<GDat>*


Delete
<GDatInd>*


Delete
<GL>*


Delete
<GLZip>*


Delete
<GPS>*


Delete
<GRC>*


Delete
<HKY>*


Delete
<Hunk>*


Delete
<HunkInd>*


Delete
<Installed>*


Delete
<ISAM>*


Delete
<JSC>*


Delete
<Kris>*


Delete
<KrisInd>*


Delete
<Krs>*


Delete
<Mail.Admin>*


Delete
<Mail.Andre>*


Delete
<Mail.Board>*


Delete
<Mail.Cape>*


Delete
<Mail.Daryl>*


Delete
<Mail.Dead>*


Delete
<Mail.DrFax>*


Delete
<Mail.Esme>*


Delete
<Mail.Garth>*


Delete
<Mail.Heidi>*


Delete
<Mail.John>*


Delete
<Mail.Lee>*


Delete
<Mail.Linbro>*


Delete
<Mail.Lynn>*


Delete
<Mail.Maggie>*


Delete
<Mail.Marco>*


Delete
<Mail.Memo>*


Delete
<Mail.Mike>*


Delete
<Mail.Natal>*


Delete
<Mail.Nathani>*


Delete
<Mail.Rosa>*


Delete
<Mail.SafCape>*


Delete
<Mail.Sam>*


Delete
<Mail.Sched>*


Delete
<Mail.Shaun>*


Delete
<Mail.ShaunC>*


Delete
<Mail.Steve>*


Delete
<Mail.Steven>*


Delete
<Mail.Store>*


Delete
<Mail.Store2>*


Delete
<Mail.Store3>*


Delete
<Mail.Store4>*


Delete
<Mail.Susan>*


Delete
<Mail.XFaxes>*


Delete
<Mail.Yvonne>*


Delete
<MailService>*


Delete
<MI>*


Delete
<Organizer>*


Delete
<Orx>*


Delete
<Oryx>*


Delete
<OryxInd>*


Delete
<PFD>*


Delete
<Program>*


Delete
<PS01>*


Delete
<PS02>*


Delete
<PS03>*


Delete
<PS04>*


Delete
<PS05>*


Delete
<PS06>*


Delete
<PS07>*


Delete
<PS08>*


Delete
<PS09>*


Delete
<PS10>*


Delete
<PS11>*


Delete
<PS12>*


Delete
<Qtm>*


Delete
<Qutm>*


Delete
<QutmInd>*


Delete
<RqTCP>*


Delete
<Safi>*


Delete
<SafiInd>*


Delete
<Sfc>*


Delete
<Sfi>*


Delete
<Sfj>*


Delete
<Spl>*


Delete
<SPSoft>*


Delete
<Sys>*


Delete
<Tax>*


Delete
<TCP>*


Delete
<TCP/IP.CSock>*


Delete
<TCP/IP.FAPI>*


Delete
<TCP/IP.FTP>*


Delete
<TCP/IP.Sock>*


Delete
<Temp>*


Delete
<VPC>*


Delete
<WG>*


Delete
<WP>*


Delete
<WPSja>*


Delete
<XFax>*


Delete
<XFaxFile>*


Path
New
Program


***** COPY OF FILES INTO SPECIFIED DIRECTORIES STARTS *****

*** COPY OF <SYS> FILES ARE FIRST *******
 
Lcopy
[D0]<Sys>*

<Sys>

Y


y


Lcopy
[D0]<6Bar>*

<6Bar>

Y


y
Lcopy
[D0]<6BarInd>*

<6BarInd>

Y


y
Lcopy
[D0]<6Br>*

<6Br>

Y


y
Lcopy
[D0]<APTNet>*

<APTNet>

Y


y
Lcopy
[D0]<APTNetGen>*

<APTNetGen>

Y


y

Lcopy
[D0]<Beltel>*

<Beltel>

Y


y

Lcopy
[D0]<Booze>*

<Booze>

Y


y


Lcopy
[D0]<cobol2>*

<cobol2>

Y


y

Lcopy
[D0]<Comp2000>*

<Comp2000>

Y


y

Lcopy
[D0]<Comp2001>*

<Comp2001>

Y


y

Lcopy
[D0]<Comp2002>*

<Comp2002>

Y


y

Lcopy
[D0]<Company>*

<Company>

Y


y

Lcopy
[D0]<Cr>*

<Cr>

Y


y

Lcopy
[D0]<CrZip>*

<CrZip>

Y


y

Lcopy
[D0]<CTC>*

<CTC>

Y


y

Lcopy
[D0]<CTJ>*

<CTJ>

Y


y

Lcopy
[D0]<CTN>*

<CTN>

Y


y

Lcopy
[D0]<Data>*

<Data>

Y


y

Lcopy
[D0]<DataInd>*

<DataInd>

Y


y

Lcopy
[D0]<DB>*

<DB>

Y


y

Lcopy
[D0]<Dr>*

<Dr>

Y


y

Lcopy
[D0]<DrZip>*

<DrZip>

Y


y

Lcopy
[D0]<Exec>*

<Exec>

Y


y

Lcopy
[D0]<Fms.FP>*

<Fms.FP>




y

Lcopy
[D0]<Forms>*

<Forms>




y

Lcopy
[D0]<FormsC>*

<FormsC>

Y


y

Lcopy
[D0]<FPlus>*

<FPlus>

Y


y

Lcopy
[D0]<FSE>*

<FSE>

Y


y

Lcopy
[D0]<GDat>*

<GDat>

Y


y

Lcopy
[D0]<GDatInd>*

<GDatInd>

Y


y

Lcopy
[D0]<GL>*

<GL>

Y


y

Lcopy
[D0]<GlZip>*

<GlZip>

Y


y

Lcopy
[D0]<GPS>*

<GPS>

Y


y

Lcopy
[D0]<GRC>*

<GRC>

Y


y

Lcopy
[D0]<HKY>*

<HKY>

Y


y

Lcopy
[D0]<Hunk>*

<Hunk>

Y


y

Lcopy
[D0]<HunkInd>*

<HunkInd>

Y


y

Lcopy
[D0]<Installed>*

<Installed>

Y


y

Lcopy
[D0]<ISAM>*

<ISAM>

Y


y
 
Lcopy
[D0]<JSC>*

<JSC>

Y


y
 
 
Lcopy
[D0]<Kris>*

<Kris>

Y


y
 
 
Lcopy
[D0]<KrisInd>*

<KrisInd>

Y


y
 
 
Lcopy
[D0]<Krs>*

<Krs>

Y


y
 
Lcopy
[D0]<Mail.Admin>*

<Mail.Admin>

Y


y
 
Lcopy
[D0]<Mail.Andre>*

<Mail.Andre>

Y


y

Lcopy
[D0]<Mail.Board>*

<Mail.Board>

Y


y
 
Lcopy
[D0]<Mail.Cape>*

<Mail.Cape>

Y


y
 
Lcopy
[D0]<Mail.Daryl>*

<Mail.Daryl>

Y


y
 
Lcopy
[D0]<Mail.Dead>*

<Mail.Dead>

Y


y
 
Lcopy
[D0]<Mail.DrFax>*

<Mail.DrFax>

Y


y
 
Lcopy
[D0]<Mail.Esme>*

<Mail.Esme>

Y


y
 
Lcopy
[D0]<Mail.Garth>*

<Mail.Garth>

Y


y
 
Lcopy
[D0]<Mail.Heidi>*

<Mail.Heidi>

Y


y
 
Lcopy
[D0]<Mail.John>*

<Mail.John>

Y


y
 
Lcopy
[D0]<Mail.Lee>*

<Mail.Lee>

Y


y
 
Lcopy
[D0]<Mail.Linbro>*

<Mail.Linbro>

Y


y
 
Lcopy
[D0]<Mail.Lynn>*

<Mail.Lynn>

Y


y
 
Lcopy
[D0]<Mail.Maggie>*

<Mail.Maggie>

Y


y
 
Lcopy
[D0]<Mail.Marco>*

<Mail.Marco>

Y


y
 
Lcopy
[D0]<Mail.Memo>*

<Mail.Memo>

Y


y
 
Lcopy
[D0]<Mail.Mike>*

<Mail.Mike>

Y


y
 
 
Lcopy
[D0]<Mail.Natal>*

<Mail.Natal>

Y


y
 
Lcopy
[D0]<Mail.Nathani>*

<Mail.Nathani>

Y


y
 
Lcopy
[D0]<Mail.Rosa>*

<Mail.Rosa>

Y


y
 
Lcopy
[D0]<Mail.Safcape>*

<Mail.SafCape>

Y


y
 
Lcopy
[D0]<Mail.Sam>*

<Mail.Sam>

Y


y
 
Lcopy
[D0]<Mail.Sched>*

<Mail.Sched>

Y


y
 
Lcopy
[D0]<Mail.Shaun>*

<Mail.Shaun>

Y


y
 
Lcopy
[D0]<Mail.ShaunC>*

<Mail.ShaunC>

Y


y
 
Lcopy
[D0]<Mail.Steve>*

<Mail.Steve>

Y


y
 
Lcopy
[D0]<Mail.Steven>*

<Mail.Steven>

Y


y
 
Lcopy
[D0]<Mail.Store>*

<Mail.Store>

Y


y
 
Lcopy
[D0]<Mail.Store2>*

<Mail.Store2>

Y


y
 
Lcopy
[D0]<Mail.Store3>*

<Mail.Store3>

Y


y
 
Lcopy
[D0]<Mail.Store4>*

<Mail.Store4>

Y


y
 
Lcopy
[D0]<Mail.Susan>*

<Mail.Susan>

Y


y
 
Lcopy
[D0]<Mail.XFaxes>*

<Mail.XFaxes>

Y


y
 
Lcopy
[D0]<Mail.Yvonne>*

<Mail.Yvonne>

Y


y
 
Lcopy
[D0]<MailService>*

<MailService>

Y


y
 
Lcopy
[D0]<Mi>*

<Mi>

Y


y
 
Lcopy
[D0]<Organizer>*

<Organizer>

Y


y
 
Lcopy
[D0]<Orx>*

<Orx>

Y


y
 
Lcopy
[D0]<Oryx>*

<Oryx>

Y


y
 
Lcopy
[D0]<OryxInd>*

<OryxInd>

Y


y
 
Lcopy
[D0]<PFD>*

<PFD>

Y


y
 
Lcopy
[D0]<Program>*

<Program>

Y


y
 
Lcopy
[D0]<PS01>*

<Ps01>

Y


y
 
Lcopy
[D0]<PS02>*

<Ps02>

Y


y
 
Lcopy
[D0]<PS03>*

<Ps03>

Y


y
 
Lcopy
[D0]<PS04>*

<Ps04>

Y


y
 
Lcopy
[D0]<PS05>*

<Ps05>

Y


y
 
Lcopy
[D0]<PS06>*

<Ps06>

Y


y
 
Lcopy
[D0]<PS07>*

<Ps07>

Y


y
 
Lcopy
[D0]<PS08>*

<Ps08>

Y


y
 
Lcopy
[D0]<PS09>*

<Ps09>

Y


y
 
Lcopy
[D0]<PS10>*

<Ps10>

Y


y
 
Lcopy
[D0]<PS11>*

<Ps11>

Y


y
 
 
Lcopy
[D0]<PS12>*

<Ps12>

Y


y
 
Lcopy
[D0]<Qtm>*

<Qtm>

Y


y
 
Lcopy
[D0]<Qutm>*

<Qutm>

Y


y
 
Lcopy
[D0]<QutmInd>*

<QutmInd>

Y


y
Lcopy
[D0]<RqTCP>*

<RqTCP>

Y


y
 
 
Lcopy
[D0]<Safi>*

<Safi>

Y


y
 
 
Lcopy
[D0]<SafiInd>*

<SafiInd>

Y


y
 
 
Lcopy
[D0]<SFC>*

<SFC>

Y


y
 
Lcopy
[D0]<SFI>*

<SFI>

Y


y
 
Lcopy
[D0]<SFJ>*

<SFJ>

Y


y

Lcopy
[D0]<SPSoft>*

<SPSoft>

Y


y
 
Lcopy
[D0]<Tax>*

<Tax>

Y


y
 
Lcopy
[D0]<TCP>*

<TCP>

Y


y
 
Lcopy
[D0]<TCP/IP.CSock>*

<TCP/IP.CSock>

Y


y
 
Lcopy
[D0]<TCP/IP.Fapi>*

<TCP/IP.Fapi>

Y


y
 
Lcopy
[D0]<TCP/IP.FTP>*

<TCP/IP.FTP>

Y


y
 
Lcopy
[D0]<TCP/IP.Sock>*

<TCP/IP.Sock>

Y


y
 
 
Lcopy
[D0]<Temp>*

<Temp>

Y


y
 
Lcopy
[D0]<VPC>*

<VPC>

Y


y
 
Lcopy
[D0]<WG>*

<WG>

Y


y
 
Lcopy
[D0]<Wp>*

<Wp>

Y


y
 
Lcopy
[D0]<WpSja>*

<WpSja>

Y


y

 
Lcopy
[D0]<XFax>*

<XFax>

Y


y

 
Lcopy
[D0]<XFaxFile>*

<XFaxFile>

Y


y
 


******* COPY OF FILES TO [D1] COMPLETE *******
