Screen Setup

Y


Y

100

Path
D1
Sys

Orthello



Cr dir
$000
15
300

Cr dir
$Gps
15
50

Cr dir
6Bar
15
100

Cr dir
6BarInd
15
100

Cr dir
6Br
15
75

Cr dir
APTNet
15
75

Cr dir
APTNetGen
15
75

Cr dir
Beltel
15
75

Cr dir
Booze
15
5

Cr dir
Cobol2
15
75

Cr dir
Company
15
150

Cr dir
Comp2000
15
75

Cr dir
Comp2001
15
125

Cr dir
CR
15
200

Cr dir
CRZip
15
75

Cr dir
CTC
15
100

Cr dir
CTJ
15
100

Cr dir
CTN
15
100

Cr dir
Data
15
100

Cr dir
DataInd
15
100

Cr dir
DB
15
100

Cr dir
Dr
15
400

Cr dir
DrZip
15
75

Cr dir
Exec
15
75

Cr dir
Fms.Fp
15
25

Cr dir
Forms
15
25

Cr dir
Formsc
15
50

Cr dir
FPlus
15
150

Cr dir
FSE
15
50

Cr dir
GDat
15
100

Cr dir
GDatInd
15
100

Cr dir
GL
15
200

Cr dir
GLZip
15
75

Cr dir
GPS
15
200

Cr dir
GRC
15
100

Cr dir
HKY
15
100

Cr dir
Hunk
15
100

Cr dir
HunkInd
15
100

Cr dir
Installed
15
200

Cr dir
ISAM
15
50

Cr dir
JSC
15
75

Cr dir
Mail.Admin
15
50

Cr dir
Mail.Andre
15
75

Cr dir
Mail.Belinda
15
75

Cr dir
Mail.Board
15
75

Cr dir
Mail.Cape
15
75

Cr dir
Mail.Daryl
15
75

Cr dir
Mail.Dead
15
75

Cr dir
Mail.Don
15
75

Cr dir
Mail.DrFax
15
75

Cr dir
Mail.Erika
15
75

Cr dir
Mail.Esme
15
75

Cr dir
Mail.Garth
15
75

Cr dir
Mail.Gavin
15
75

Cr dir
Mail.Gys
15
75

Cr dir
Mail.Heidi
15
200

Cr dir
Mail.John
15
200

Cr dir
Mail.Lee
15
100

Cr dir
Mail.Linbro
15
75

Cr dir
Mail.Lynn
15
75

Cr dir
Mail.Maggie
15
75

Cr dir
Mail.Mark
15
75

Cr dir
Mail.Memo
15
25

Cr dir
Mail.Natal
15
25

Cr dir
Mail.Oliver
15
150

Cr dir
Mail.Rosa
15
75

Cr dir
Mail.SafCape
15
25

Cr dir
Mail.Sam
15
75

Cr dir
Mail.Sched
15
25

Cr dir
Mail.Shaun
15
75

Cr dir
Mail.Sibu
15
75

Cr dir
Mail.Stef
15
75

Cr dir
Mail.Steve
15
100

Cr dir
Mail.Steven
15
75

Cr dir
Mail.Store
15
75

Cr dir
Mail.Store2
15
75

Cr dir
Mail.Store3
15
75

Cr dir
Mail.Store4
15
75

Cr dir
Mail.Susan
15
75

Cr dir
Mail.Vanes
15
75

Cr dir
Mail.XFaxes
15
25

Cr dir
Mail.Yvonne
15
75

Cr dir
MailService
15
75

Cr dir
MI
15
200

Cr dir
Organizer
15
100

Cr dir
Orx
15
75

Cr dir
Oryx
15
100

Cr dir
OryxInd
15
100

Cr dir
PFD
15
75

Cr dir
Program
15
600

Cr dir
PS01
15
2000

Cr dir
PS02
15
200

Cr dir
PS03
15
75

Cr dir
PS04
15
75

Cr dir
PS05
15
75

Cr dir
PS06
15
75

Cr dir
PS07
15
75

Cr dir
PS08
15
25

Cr dir
PS09
15
25

Cr dir
PS10
15
25

Cr dir
PS11
15
25

Cr dir
Qtm
15
75

Cr dir
Qutm
15
100

Cr dir
QutmInd
15
100

Cr dir
Sfc
15
75

Cr dir
Sfj
15
75

Cr dir
Spl
15
500

Cr dir
SPSoft
15
50

Cr dir
Tax
15
100

Cr dir
Temp
15
100

Cr dir
VPC
15
25

Cr dir
WG
15
75

Cr dir
WP
15
750

Cr dir
WPSja
15
300

Cr dir
XFax
15
200

Cr dir
XFaxFile
15
500

Path
D1
Program

***** COPY OF FILES INTO SPECIFIED DIRECTORIES STARTS *****

Lcopy
[D0]<6Bar>*

<6Bar>

Y


y
Lcopy
[D0]<6BarInd>*

<6BarInd>

Y


y
Lcopy
[D0]<6Br>*

<6Br>

Y


y
Lcopy
[D0]<APTNet>*

<APTNet>

Y


y
Lcopy
[D0]<APTNetGen>*

<APTNetGen>

Y


y

Lcopy
[D0]<Beltel>*

<Beltel>

Y


y

Lcopy
[D0]<Booze>*

<Booze>

Y


y


Lcopy
[D0]<cobol2>*

<cobol2>

Y


y

Lcopy
[D0]<Company>*

<Company>

Y


y

Lcopy
[D0]<Comp2000>*

<Comp2000>

Y


y

Lcopy
[D0]<Comp2001>*

<Comp2001>

Y


y

Lcopy
[D0]<Cr>*

<Cr>

Y


y

Lcopy
[D0]<CrZip>*

<CrZip>

Y


y

Lcopy
[D0]<CTC>*

<CTC>

Y


y

Lcopy
[D0]<CTJ>*

<CTJ>

Y


y

Lcopy
[D0]<CTN>*

<CTN>

Y


y

Lcopy
[D0]<Data>*

<Data>

Y


y

Lcopy
[D0]<DataInd>*

<DataInd>

Y


y

Lcopy
[D0]<DB>*

<DB>

Y


y

Lcopy
[D0]<Dr>*

<Dr>

Y


y

Lcopy
[D0]<DrZip>*

<DrZip>

Y


y

Lcopy
[D0]<Exec>*

<Exec>

Y


y

Lcopy
[D0]<Fms.FP>*

<Fms.FP>




y

Lcopy
[D0]<Forms>*

<Forms>




y

Lcopy
[D0]<FormsC>*

<FormsC>

Y


y

Lcopy
[D0]<FPlus>*

<FPlus>

Y


y

Lcopy
[D0]<FSE>*

<FSE>

Y


y

Lcopy
[D0]<GDat>*

<GDat>

Y


y

Lcopy
[D0]<GDatInd>*

<GDatInd>

Y


y

Lcopy
[D0]<GL>*

<GL>

Y


y

Lcopy
[D0]<GlZip>*

<GlZip>

Y


y

Lcopy
[D0]<GPS>*

<GPS>

Y


y

Lcopy
[D0]<GRC>*

<GRC>

Y


y

Lcopy
[D0]<HKY>*

<HKY>

Y


y

Lcopy
[D0]<Hunk>*

<Hunk>

Y


y

Lcopy
[D0]<HunkInd>*

<HunkInd>

Y


y

Lcopy
[D0]<Installed>*

<Installed>

Y


y

Lcopy
[D0]<ISAM>*

<ISAM>

Y


y
 
Lcopy
[D0]<JSC>*

<JSC>

Y


y
 
Lcopy
[D0]<Mail.Admin>*

<Mail.Admin>

Y


y
 
Lcopy
[D0]<Mail.Andre>*

<Mail.Andre>

Y


y

Lcopy
[D0]<Mail.Board>*

<Mail.Board>

Y


y
 
Lcopy
[D0]<Mail.Cape>*

<Mail.Cape>

Y


y
 
Lcopy
[D0]<Mail.Daryl>*

<Mail.Daryl>

Y


y
 
Lcopy
[D0]<Mail.Dead>*

<Mail.Dead>

Y


y
 
Lcopy
[D0]<Mail.DrFax>*

<Mail.DrFax>

Y


y
 
Lcopy
[D0]<Mail.Erika>*

<Mail.Erika>

Y


y
 
Lcopy
[D0]<Mail.Esme>*

<Mail.Esme>

Y


y
 
Lcopy
[D0]<Mail.Garth>*

<Mail.Garth>

Y


y
 
Lcopy
[D0]<Mail.Gavin>*

<Mail.Gavin>

Y


y
 
Lcopy
[D0]<Mail.Gys>*

<Mail.Gys>

Y


y
 
Lcopy
[D0]<Mail.Heidi>*

<Mail.Heidi>

Y


y
 
Lcopy
[D0]<Mail.John>*

<Mail.John>

Y


y
 
Lcopy
[D0]<Mail.Lee>*

<Mail.Lee>

Y


y
 
Lcopy
[D0]<Mail.Linbro>*

<Mail.Linbro>

Y


y
 
Lcopy
[D0]<Mail.Lynn>*

<Mail.Lynn>

Y


y
 
Lcopy
[D0]<Mail.Maggie>*

<Mail.Maggie>

Y


y
 
Lcopy
[D0]<Mail.Mark>*

<Mail.Mark>

Y


y
 
Lcopy
[D0]<Mail.Memo>*

<Mail.Memo>

Y


y
 
Lcopy
[D0]<Mail.Natal>*

<Mail.Natal>

Y


y
 
Lcopy
[D0]<Mail.Oliver>*

<Mail.Oliver>

Y


y
 
Lcopy
[D0]<Mail.Rosa>*

<Mail.Rosa>

Y


y
 
Lcopy
[D0]<Mail.Safcape>*

<Mail.SafCape>

Y


y
 
Lcopy
[D0]<Mail.Sam>*

<Mail.Sam>

Y


y
 
Lcopy
[D0]<Mail.Sched>*

<Mail.Sched>

Y


y
 
Lcopy
[D0]<Mail.Shaun>*

<Mail.Shaun>

Y


y
 
Lcopy
[D0]<Mail.Sibu>*

<Mail.Sibu>

Y


y
 
Lcopy
[D0]<Mail.Stef>*

<Mail.Stef>

Y


y
 
Lcopy
[D0]<Mail.Steve>*

<Mail.Steve>

Y


y
 
Lcopy
[D0]<Mail.Steven>*

<Mail.Steven>

Y


y
 
Lcopy
[D0]<Mail.Store>*

<Mail.Store>

Y


y
 
Lcopy
[D0]<Mail.Store2>*

<Mail.Store2>

Y


y
 
Lcopy
[D0]<Mail.Store3>*

<Mail.Store3>

Y


y
 
Lcopy
[D0]<Mail.Store4>*

<Mail.Store4>

Y


y
 
Lcopy
[D0]<Mail.Susan>*

<Mail.Susan>

Y


y
 
Lcopy
[D0]<Mail.XFaxes>*

<Mail.XFaxes>

Y


y
 
Lcopy
[D0]<Mail.Yvonne>*

<Mail.Yvonne>

Y


y
 
Lcopy
[D0]<MailService>*

<MailService>

Y


y
 
Lcopy
[D0]<Mi>*

<Mi>

Y


y
 
Lcopy
[D0]<Organizer>*

<Organizer>

Y


y
 
Lcopy
[D0]<Orx>*

<Orx>

Y


y
 
Lcopy
[D0]<Oryx>*

<Oryx>

Y


y
 
Lcopy
[D0]<OryxInd>*

<OryxInd>

Y


y
 
Lcopy
[D0]<PFD>*

<PFD>

Y


y
 
Lcopy
[D0]<Program>*

<Program>

Y


y
 
Lcopy
[D0]<PS01>*

<Ps01>

Y


y
 
Lcopy
[D0]<PS02>*

<Ps02>

Y


y
 
Lcopy
[D0]<PS03>*

<Ps03>

Y


y
 
Lcopy
[D0]<PS04>*

<Ps04>

Y


y
 
Lcopy
[D0]<PS05>*

<Ps05>

Y


y
 
Lcopy
[D0]<PS06>*

<Ps06>

Y


y
 
Lcopy
[D0]<PS07>*

<Ps07>

Y


y
 
Lcopy
[D0]<PS08>*

<Ps08>

Y


y
 
Lcopy
[D0]<PS09>*

<Ps09>

Y


y
 
Lcopy
[D0]<PS10>*

<Ps10>

Y


y
 
Lcopy
[D0]<PS11>*

<Ps11>

Y


y
 
Lcopy
[D0]<Qtm>*

<Qtm>

Y


y
 
Lcopy
[D0]<Qutm>*

<Qutm>

Y


y
 
Lcopy
[D0]<QutmInd>*

<QutmInd>

Y


y
Lcopy
[D0]<RqTCP>*

<RqTCP>

Y


y
 
 
Lcopy
[D0]<SFC>*

<SFC>

Y


y
 
Lcopy
[D0]<SFJ>*

<SFJ>

Y


y
 
Lcopy
[D0]<Spl>*

<Spl>

Y


y
 
Lcopy
[D0]<SPSoft>*

<SPSoft>

Y


y
 
Lcopy
[D0]<Sys>*

<Sys>

Y


y
 
Lcopy
[D0]<Tax>*

<Tax>

Y


y
 
Lcopy
[D0]<Tax>*

<Tax>

Y


y
 
Lcopy
[D0]<TCP>*

<TCP>

Y


y
 
Lcopy
[D0]<TCP/IP.Sock>*

<TCP/IP.Sock>

Y


y
 
Lcopy
[D0]<TCP/IP.Sock>*

<TCP/IP.Sock>

Y


y
 
Lcopy
[D0]<TCP/IP.Sock>*

<TCP/IP.Sock>

Y


y
 
Lcopy
[D0]<TCP/IP.Sock>*

<TCP/IP.Sock>

Y


y
 
 
Lcopy
[D0]<Temp>*

<Temp>

Y


y
 
Lcopy
[D0]<VPC>*

<VPC>

Y


y
 
Lcopy
[D0]<WG>*

<WG>

Y


y
 
Lcopy
[D0]<Wp>*

<Wp>

Y


y
 
Lcopy
[D0]<WpSja>*

<WpSja>

Y


y

 
Lcopy
[D0]<XFax>*

<XFax>

Y


y

 
Lcopy
[D0]<XFaxFile>*

<XFaxFile>

Y


y
 


******* COPY OF FILES COMPLETE *******
