Screen Setup

Yes


Yes

100
Type
<Temp>CTJMessage
Path
Win
CTJ

Del
<Image>*

/z
*
MonthEnd1.Zip
Rename
DBprintCo01
<Image>InCo01
Rename
DrLaserCo01
<Image>StCo01
Delete
S* D*

Type
<Temp>GRCMessage
Path
Win
GRC
/z
*
MonthEnd2.Zip
Rename
DBprintCo02
<Image>InCo02
Rename
DrLaserCo02
<Image>StCo02
Delete
S* D*

Type
<Temp>CTNMessage
Path
Win
CTN
Delete
s*  d*
/u
Mo*.zip
db* drl*

Rename
DBprintCo03
<Image>InCo03
Rename
DrLaserCo03
<Image>StCo03

Type
<Temp>ORXMessage
Path
Win
Orx
/z
*
MonthEnd5.Zip
Rename
DBprintCo05
<Image>InCo05
Rename
DrLaserCo05
<Image>StCo05
Delete
S* D*


Type
<Temp>SFJMessage
Path
Win
SFJ
Delete
s*  d*
/u
Mo*.zip
db* drl*

Rename
DBprintCo07
<Image>InCo07
Rename
DrLaserCo07
<Image>StCo07

Type
<Temp>CSCMessage
Path
Win
CSC
Delete
s*  d*
/u
Mo*.zip
db* drl*

Rename
DBprintCo08
<Image>InCo08
Rename
DrLaserCo08
<Image>StCo08

Type
<Temp>SFIMessage
Path
Win
SFI
/z
*
MonthEnd9.Zip
Delete
S* D*

Type
<Temp>QTMMessage
Path
Win
Qtm
/z
*
MonthEnd10.Zip
Delete
S* D*

Type
<Temp>HKYMessage
Path
Win
HKY
/z
*
MonthEnd11.Zip
Delete
S* D*

Type
<Temp>KRSMessage
Path
Win
KRS
/z
*
MonthEnd12.Zip
Delete
S* D*

Path
Win
Program
Video

Type
<Temp>DocuFinalMessage

Submit
Unzip*sub
1
