Screen Setup

Y


Y

100


Path
Win
Zip

Orthello



Type
<Temp>ZipMessage1

1

Delete
[f0]<Src>*
No

LCopy
1*Zip

[f0]<Src>

Yes


Yes
Type
<Temp>ZipMessage2-1

1

Delete
[f0]<Src>*
No


LCopy
2*Zip

[f0]<Src>

Yes


Yes
Type
<Temp>ZipMessage3-1

1

Delete
[f0]<Src>*
No


LCopy
3*Zip

[f0]<Src>

Yes


Yes
Type
<Temp>ZipMessage4

1

Delete
[f0]<Src>*
No


LCopy
4*Zip

[f0]<Src>

Yes


Yes
Type
<Temp>ZipMessage5

1
Delete
[f0]<Program>* [f0]<Temp>* [f0]<Copy>* [f0]<Chlfd>*
No


LCopy
5Chlfd*Zip

[f0]<Chlfd>

Yes


Yes

LCopy
5Temp*Zip

[f0]<Temp>

Yes


Yes


LCopy
5Sub*Zip

[f0]<Program>

Yes


Yes

LCopy
CoForms.Lib

[f0]<Program>

Yes


Yes

Path
Win
Program

****** LCopy Of ALL zip files complete *****
