Path
Win
Sys

Screen Setup

Y


Y




Set Pro
.User
3
Orthello

Set Pro
Accounts.User
3
Accounts

Set Pro
Andre.User
3
Kawasaki

Set Pro
APTNet.User
3
Cash

Set Pro
Backup.User
3
Backup

Set Pro
BoozeClub.User
3
Beer

Set Pro
Counter*.User
3
Cash

Set Pro
Daryl.User
3
Oryx

Set Pro
DiskSquash.User
3
Orthello

Set Pro
Donovan.User
3
Blakkie

Set Pro
DrFaxes.User
3
Cash

Set Pro
Erika.User
3
Shanti

Set Pro
Etienne.User
3
BigProfits

Set Pro
Garrarc.User
3
Bags

Set Pro
JCMirror.User
3
Cash

Set Pro
John.User
3
ThrCanBOnly1

Set Pro
Lizzie.User
3
Arnie

Set Pro
Lynn.User
3
LGE-Cr

Set Pro
Master.User
3
Cash

Set Pro
PrintServer.User
15
''

Set Pro
Ray.User
3
Coelecanth

Set Pro
Raymond.User
3
Frodo

Set Pro
Reinhardt.User
3
BlueBulls

Set Pro
Rosa.User
3
NewAcc

Set Pro
RPMirror.User
3
Cash

Set Pro
Sam.User
3
Bucs

Set Pro
Samantha.User
3
Reception

Set Pro
SCMirror.User
3
Orthello

Set Pro
SHMirror.User
3
Cash

Set Pro
SJC1.User
3
Orthello

Set Pro
Spl.User
3
Cash

Set Pro
SplCheque.User
3
Cash

Set Pro
SplCntr.User
3
Cash

Set Pro
SplGRC.User
3
Cash

Set Pro
SplLabel.User
3
Security

Set Pro
SplMaster.User
15
''

Set Pro
SplStore*.User
3
Security

Set Pro
SplWp.User
3
Cash

Set Pro
Steve.User
3
Orthello

Set Pro
Store*.User
3
Security

Set Pro
Stuart.User
3
Arsenal

Set Pro
Tony.User
3
Service

Set Pro
XFax.User
3
Cash

Set Pro
XFaxDeInstall.User
3
Cash

Set Pro
XFaxInstall.User
3
Cash

Set Pro
Yvonne.User
3
YW-DR

Set Pro
YWMirror.User
3
Cash


Path
Win
Program

********** PASSWORDS SET TO NEW VALUES, COMPLETE *******
