Screen Setup

y


Y

100

Path
Win
CTJ
/u
*.zip
@<Temp>Unzip1.Fls


Path
Win
GRC
/u
Mo*.zip
@<Temp>Unzip1.Fls


Path
Win
CTN
/u
Mo*.zip
@<Temp>Unzip1.Fls


Path
Win
ORX
/u
Mo*.zip
@<Temp>Unzip1.Fls


Path
Win
SFJ
/u
Mo*.zip
@<Temp>Unzip1.Fls


Path
Win
CSC
/u
Mo*.zip
@<Temp>Unzip1.Fls


Path
Win
SFI
/u
Mo*.zip
@<Temp>Unzip2.Fls


Path
Win
QTM
/u
Mo*.zip
@<Temp>Unzip2.Fls


Path
Win
HKY
/u
Mo*.zip
@<Temp>Unzip2.Fls


Path
Win
KRS
/u
Mo*.zip
@<Temp>Unzip2.Fls




Path
Win
Program

Vid

Type
<Temp>UnZipFilesMessage

Submit
BranchStat.sub
1

