Screen Setup

Y


Y

100

Delete
<*>*-old <*>*.Idy <*>*.lst <*>*.Tmp


Path
Win
NewSrc

Orthello



Type
<Temp>ZipMessage1

1

/zip
dr*src
[f0]<Src>Dr.Zip
Y


Type
<Temp>ZipMessage2

1

/zip
St*src
[f0]<Src>St.Zip
Y



Type
<Temp>ZipMessage3

1

/zip
Sl*src
[f0]<Src>Sl.Zip
Y



Type
<Temp>ZipMessage4

1

/zip
Gl*src
[f0]<Src>Gl.Zip
Y

/zip
Cb*src
[f0]<Src>Cb.Zip
Y


/zip
Cr*src
[f0]<Src>Cr.Zip
Y


/zip
Bm*src
[f0]<Src>Bm.Zip
Y

/zip
*menu*Src *pass*src
[f0]<Src>Menu.Zip
Y


/zip
Co*Src
[f0]<Src>Co.Zip
Y



Type
<Temp>ZipMessage5

1

/zip
<copy>*
[f0]<Copy>Copy.Zip
Y



/zip
Chlfd*
[f0]<Chlfd>Chlfd.Zip
Y

Lcop
[Win]<Program>CoForms.Lib

[f0]<Program>

Y

/zip
<Program>*.sub*
[f0]<Program>Sub.Zip
Y

/zip
<Temp>*
[f0]<Temp>Temp.Zip
Y

****** zip of all files complete *****
