Screen Setup

Y


Y

100

Delete
<*>*-old <*>*.Idy <*>*.lst <*>*.Tmp


Path
Win
NewSrc

Orthello



Type
<Temp>ZipMessage1

1

/zip
dr*src
[Win]<Zip>1Dr.Zip
Y


Type
<Temp>ZipMessage2

1

/zip
St*src
[Win]<Zip>2St.Zip
Y



Type
<Temp>ZipMessage3

1

/zip
Sl*src
[Win]<Zip>3Sl.Zip
Y



Type
<Temp>ZipMessage4

1

/zip
Gl*src
[Win]<Zip>4Gl.Zip
Y

/zip
Cb*src
[Win]<Zip>4Cb.Zip
Y


/zip
Cr*src
[Win]<Zip>4Cr.Zip
Y


/zip
Bm*src
[Win]<Zip>4Bm.Zip
Y

/zip
*menu*Src *pass*src
[Win]<Zip>4Menu.Zip
Y


/zip
Co*Src
[Win]<Zip>4Co.Zip
Y



Type
<Temp>ZipMessage5

1

/zip
<copy>*
[Win]<Zip>5Copy.Zip
Y



/zip
Chlfd*
[Win]<Zip>5Chlfd.Zip
Y

Lcop
[Win]<Program>CoForms.Lib

[Win]<Zip>

Y

/zip
<Program>*.sub*
[Win]<Zip>5Sub.Zip
Y

/zip
<Temp>*
[Win]<Zip>5Temp.Zip
Y

****** zip of all files to <Zip> complete *****
